<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-11T15:43:19 UTC" name="Surefire suite" finished-at="2021-10-11T15:43:19 UTC" duration-ms="46">
    <groups>
    </groups>
    <test started-at="2021-10-11T15:43:19 UTC" name="Surefire test" finished-at="2021-10-11T15:43:19 UTC" duration-ms="46">
      <class name="flipkart.server.ValidationsTest">
        <test-method is-config="true" signature="openSessionsAndStartModificationTracker()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:18 UTC" name="openSessionsAndStartModificationTracker" finished-at="2021-10-11T15:43:19 UTC" duration-ms="847" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[no backend found -> no tests]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: no backend found -> no tests
at org.tentackle.test.pdo.AbstractPdoTest.openSession(AbstractPdoTest.java:235)
at org.tentackle.test.pdo.AbstractPdoTest.openSessionsAndStartModificationTracker(AbstractPdoTest.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.tentackle.session.PersistenceException: default-mgr: connection to 'PostgreSQL@jdbc:postgresql://localhost/order' failed
SQL-Message: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. (org.postgresql.util.PSQLException)
SQL-Code:    0
SQL-State:   08001
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DefaultConnectionManager.createConnection(DefaultConnectionManager.java:561)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DefaultConnectionManager.login(DefaultConnectionManager.java:271)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.Db.open(Db.java:673)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.Db.<init>(Db.java:599)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DbFactory.create(DbFactory.java:45)
at org.tentackle.pdo@11.7.0.0/org.tentackle.pdo.Pdo.createSession(Pdo.java:529)
at org.tentackle.pdo@11.7.0.0/org.tentackle.pdo.Pdo.createSession(Pdo.java:538)
at org.tentackle.test.pdo.AbstractPdoTest.openSession(AbstractPdoTest.java:231)
... 25 more
Caused by: java.sql.SQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. (org.postgresql.util.PSQLException)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
at org.postgresql.Driver.makeConnection(Driver.java:465)
at org.postgresql.Driver.connect(Driver.java:264)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at org.tentackle.sql@11.7.0.0/org.tentackle.sql.backends.AbstractBackend.createConnection(AbstractBackend.java:126)
at org.tentackle.sql@11.7.0.0/org.tentackle.sql.BackendInfo.connect(BackendInfo.java:260)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DefaultConnectionManager.createConnection(DefaultConnectionManager.java:558)
... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSessionsAndStartModificationTracker -->
        <test-method is-config="true" signature="setup()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="setup" finished-at="1970-01-01T00:00:00 UTC" duration-ms="-1633966999822" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="beforeClass" finished-at="2021-10-11T15:43:19 UTC" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="beforeMethod" finished-at="2021-10-11T15:43:19 UTC" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testValidation()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="testValidation" finished-at="2021-10-11T15:43:19 UTC" duration-ms="0" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[no backend found -> no tests]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: no backend found -> no tests
at org.tentackle.test.pdo.AbstractPdoTest.openSession(AbstractPdoTest.java:235)
at org.tentackle.test.pdo.AbstractPdoTest.openSessionsAndStartModificationTracker(AbstractPdoTest.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.tentackle.session.PersistenceException: default-mgr: connection to 'PostgreSQL@jdbc:postgresql://localhost/order' failed
SQL-Message: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. (org.postgresql.util.PSQLException)
SQL-Code:    0
SQL-State:   08001
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DefaultConnectionManager.createConnection(DefaultConnectionManager.java:561)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DefaultConnectionManager.login(DefaultConnectionManager.java:271)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.Db.open(Db.java:673)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.Db.<init>(Db.java:599)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DbFactory.create(DbFactory.java:45)
at org.tentackle.pdo@11.7.0.0/org.tentackle.pdo.Pdo.createSession(Pdo.java:529)
at org.tentackle.pdo@11.7.0.0/org.tentackle.pdo.Pdo.createSession(Pdo.java:538)
at org.tentackle.test.pdo.AbstractPdoTest.openSession(AbstractPdoTest.java:231)
... 25 more
Caused by: java.sql.SQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. (org.postgresql.util.PSQLException)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
at org.postgresql.Driver.makeConnection(Driver.java:465)
at org.postgresql.Driver.connect(Driver.java:264)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at org.tentackle.sql@11.7.0.0/org.tentackle.sql.backends.AbstractBackend.createConnection(AbstractBackend.java:126)
at org.tentackle.sql@11.7.0.0/org.tentackle.sql.BackendInfo.connect(BackendInfo.java:260)
at org.tentackle.database@11.7.0.0/org.tentackle.dbms.DefaultConnectionManager.createConnection(DefaultConnectionManager.java:558)
... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidation -->
        <test-method is-config="true" signature="restore()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="restore" finished-at="1970-01-01T00:00:00 UTC" duration-ms="-1633966999846" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restore -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="afterMethod" finished-at="2021-10-11T15:43:19 UTC" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="afterClass" finished-at="2021-10-11T15:43:19 UTC" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="closeSessionsAndTerminateModificationTracker()[pri:0, instance:flipkart.server.ValidationsTest@6c6cb480]" started-at="2021-10-11T15:43:19 UTC" name="closeSessionsAndTerminateModificationTracker" finished-at="2021-10-11T15:43:19 UTC" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSessionsAndTerminateModificationTracker -->
      </class> <!-- flipkart.server.ValidationsTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
